from __future__ import annotations

from . import semantics
from .legacy_helpers import (
    _LAYOUT_BALANCE_ROW_SPECS,
    _LAYOUT_ROW_SIGNAL_TOKENS,
    _METRIC_KEYWORDS,
    _NUMBER_PATTERN,
    _NUMBER_REGEX_FRAGMENT,
    _OCR_NUMBER_PATTERN,
)

_LINE_CODE_MAP: dict[str, str] = {
    "2110": "revenue",
    "2400": "net_profit",
    "1600": "total_assets",
    "1700": "total_assets",
    "1300": "equity",
    "1200": "current_assets",
    "1500": "short_term_liabilities",
    "1400": "long_term_liabilities",
    "1230": "accounts_receivable",
    "1210": "inventory",
    "1250": "cash_and_equivalents",
    "2120": "cost_of_goods_sold",
    "2200": "ebit",
}

_IFRS_ENGLISH_KEYWORDS: dict[str, str] = {
    "revenue": "revenue",
    "total revenue": "revenue",
    "turnover": "revenue",
    "net sales": "revenue",
    "net profit": "net_profit",
    "net income": "net_profit",
    "profit for the year": "net_profit",
    "profit for the period": "net_profit",
    "profit attributable to owners": "net_profit",
    "profit attributable to shareholders": "net_profit",
    "operating profit": "ebit",
    "ebitda": "ebitda",
    "total assets": "total_assets",
    "non-current assets": "total_assets",
    "current assets": "current_assets",
    "property, plant and equipment": "total_assets",
    "intangible assets": "total_assets",
    "total equity": "equity",
    "equity attributable to owners": "equity",
    "share capital": "equity",
    "retained earnings": "equity",
    "total shareholders' equity": "equity",
    "total liabilities": "liabilities",
    "total equity and liabilities": "liabilities",
    "current liabilities": "short_term_liabilities",
    "non-current liabilities": "long_term_liabilities",
    "trade payables": "liabilities",
    "short-term borrowings": "short_term_borrowings",
    "current borrowings": "short_term_borrowings",
    "long-term borrowings": "long_term_borrowings",
    "non-current borrowings": "long_term_borrowings",
    "short-term lease liabilities": "short_term_lease_liabilities",
    "current lease liabilities": "short_term_lease_liabilities",
    "long-term lease liabilities": "long_term_lease_liabilities",
    "non-current lease liabilities": "long_term_lease_liabilities",
    "cash and cash equivalents": "cash_and_equivalents",
    "trade receivables": "accounts_receivable",
    "inventories": "inventory",
    "stocks": "inventory",
    "finance costs": "interest_expense",
    "interest expense": "interest_expense",
}

_IFRS_APPROXIMATION_KEYWORDS: dict[str, tuple[str, str]] = {
    "gross profit": (
        "ebitda",
        semantics.REASON_GROSS_PROFIT_TO_EBITDA_APPROXIMATION,
    ),
}

_GARBLED_KEYWORDS: dict[str, str] = {
    "выручка": "revenue",
    "чистая прибыль": "net_profit",
    "прибыль за год": "net_profit",
    "прибыль за период": "net_profit",
    "итого активов": "total_assets",
    "итого активы": "total_assets",
    "итого капитала": "equity",
    "итого капитал": "equity",
    "собственный капитал": "equity",
    "денежные средства": "cash_and_equivalents",
    "запасы": "inventory",
    "дебиторская задолженность": "accounts_receivable",
    "краткосрочные обязательства": "short_term_liabilities",
    "оборотные активы": "current_assets",
    "операционная прибыль": "ebit",
    "финансовые расходы": "interest_expense",
    "себестоимость": "cost_of_goods_sold",
    "т√Ёєўър": "revenue",
    "шс√ы№ чр уюф": "net_profit",
    "шёЄр  яЁшс√ы№": "net_profit",
    "Єюую ръЄшт√": "total_assets",
    "шЄюую ъряшЄры": "equity",
    "Єюую ъряшЄры": "equity",
    "хэхцэ√х ёЁхфёЄтр": "cash_and_equivalents",
    "рярё√": "inventory",
    "хсшЄюЁёър  чрфюыцхээюёЄ№": "accounts_receivable",
    "ЁрЄъюёЁюўэ√х юс чрЄхы№ёЄтр": "short_term_liabilities",
    "сюЁюЄэ√х ръЄшт√": "current_assets",
    "юяхЁрЎшюээр  яЁшс√ы№": "ebit",
    "Їшэрэёют√х Ёрёїюф√": "interest_expense",
    "хсхёЄюшьюёЄ№": "cost_of_goods_sold",
}

_TEXT_LINE_CODE_MAP: dict[str, tuple[tuple[str, ...], tuple[str, ...] | None]] = {
    "revenue": (("2110",), ("выручка от реализации, без ндс", "выручка", "revenue")),
    "net_profit": (
        ("2400",),
        (
            "чистая прибыль",
            "чистая прибыль общества",
            "прибыль за период",
            "прибыль за год",
            "net profit",
            "net income",
        ),
    ),
    "total_assets": (("1600", "1700"), None),
    "current_assets": (("1200",), None),
    "inventory": (("1210",), ("запасы", "inventory")),
    "accounts_receivable": (
        ("1230",),
        ("дебиторская задолженность", "accounts receivable", "trade receivables"),
    ),
    "long_term_liabilities": (
        ("1400",),
        (
            "долгосрочные обязательства",
            "итого по разделу iv",
            "total non-current liabilities",
        ),
    ),
    "short_term_liabilities": (
        ("1500",),
        (
            "краткосрочные обязательства",
            "итого краткосрочных обязательств",
            "итого краткосрочные обязательства",
            "total current liabilities",
        ),
    ),
    "cash_and_equivalents": (
        ("1250",),
        ("денежные средства", "cash and cash equivalents"),
    ),
}

_MONETARY_METRICS = frozenset(
    {
        "revenue",
        "net_profit",
        "total_assets",
        "equity",
        "liabilities",
        "current_assets",
        "short_term_liabilities",
        "long_term_liabilities",
        "accounts_receivable",
        "inventory",
        "cash_and_equivalents",
        "ebitda",
        "ebit",
        "interest_expense",
        "cost_of_goods_sold",
        "short_term_borrowings",
        "long_term_borrowings",
        "short_term_lease_liabilities",
        "long_term_lease_liabilities",
    }
)

__all__ = [
    "_GARBLED_KEYWORDS",
    "_IFRS_ENGLISH_KEYWORDS",
    "_IFRS_APPROXIMATION_KEYWORDS",
    "_LAYOUT_BALANCE_ROW_SPECS",
    "_LAYOUT_ROW_SIGNAL_TOKENS",
    "_LINE_CODE_MAP",
    "_METRIC_KEYWORDS",
    "_MONETARY_METRICS",
    "_NUMBER_PATTERN",
    "_NUMBER_REGEX_FRAGMENT",
    "_OCR_NUMBER_PATTERN",
    "_TEXT_LINE_CODE_MAP",
]
