from __future__ import annotations

WAVE3_REASON_AMBIGUOUS_CANDIDATES = "wave3_ambiguous_candidates"
WAVE3_REASON_NO_CANDIDATE = "wave3_no_candidate"
WAVE3_REASON_INVALID_BASIS = "wave3_invalid_basis"
WAVE3_REASON_MISSING_OPENING_BALANCE = "wave3_missing_opening_balance"
WAVE3_REASON_MISSING_CLOSING_BALANCE = "wave3_missing_closing_balance"
WAVE3_REASON_INCOMPATIBLE_OPENING_BASIS = "wave3_incompatible_opening_basis"
WAVE3_REASON_INCOMPATIBLE_CLOSING_BASIS = "wave3_incompatible_closing_basis"
WAVE3_REASON_FORBIDDEN_APPROXIMATION = "wave3_forbidden_approximation"
WAVE3_REASON_COVERAGE_SUPPRESSED = "wave3_coverage_suppressed"
WAVE3_REASON_OUT_OF_SCOPE_OUTWARD_REFUSAL = "wave3_out_of_scope_outward_refusal"
WAVE3_REASON_REPORTED_CANDIDATE_REQUIRED = "wave3_reported_candidate_required"
WAVE3_REASON_APPROXIMATION_SEMANTICS_REQUIRED = "wave3_approximation_semantics_required"
WAVE3_REASON_UNKNOWN_AVERAGE_BALANCE_POLICY = "wave3_unknown_average_balance_policy"
WAVE3_REASON_MIXED_DEBT_BASIS = "wave3_mixed_debt_basis"
WAVE3_REASON_LEASE_LIABILITY_MIXING_FORBIDDEN = "wave3_lease_liability_mixing_forbidden"
WAVE3_REASON_COMPUTE_BASIS_MISSING = "wave3_compute_basis_missing"
WAVE3_REASON_MATH_UNIT_INCOMPATIBLE = "wave3_math_unit_incompatible"

ALL_WAVE3_REASON_CODES = frozenset(
    {
        WAVE3_REASON_AMBIGUOUS_CANDIDATES,
        WAVE3_REASON_NO_CANDIDATE,
        WAVE3_REASON_INVALID_BASIS,
        WAVE3_REASON_MISSING_OPENING_BALANCE,
        WAVE3_REASON_MISSING_CLOSING_BALANCE,
        WAVE3_REASON_INCOMPATIBLE_OPENING_BASIS,
        WAVE3_REASON_INCOMPATIBLE_CLOSING_BASIS,
        WAVE3_REASON_FORBIDDEN_APPROXIMATION,
        WAVE3_REASON_COVERAGE_SUPPRESSED,
        WAVE3_REASON_OUT_OF_SCOPE_OUTWARD_REFUSAL,
        WAVE3_REASON_REPORTED_CANDIDATE_REQUIRED,
        WAVE3_REASON_APPROXIMATION_SEMANTICS_REQUIRED,
        WAVE3_REASON_UNKNOWN_AVERAGE_BALANCE_POLICY,
        WAVE3_REASON_MIXED_DEBT_BASIS,
        WAVE3_REASON_LEASE_LIABILITY_MIXING_FORBIDDEN,
        WAVE3_REASON_COMPUTE_BASIS_MISSING,
        WAVE3_REASON_MATH_UNIT_INCOMPATIBLE,
    }
)
